name: CI Build

on:
  push:
    branches: [ "**" ]
    tags:
      - '*'
  pull_request:
    branches: [ "**" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    #container: dingodatabase/dingo-eureka:rocky9
    container: rockylinux/rockylinux:9.3

    steps:
    - uses: actions/checkout@v4

    - name: Check disk size
      run: |
        echo "Disk size init:"
        df -h

    - name: Remove .git directory
      run: |
        echo "Remove .git directory"
        rm -rf .git

    - name: Check disk size
      run: |
        echo "Disk size after remove git:"
        df -h

    - name: Config dingo-sdk env
      run: |
        echo "DINGOSDK_INSTALL_PATH=/root/.local/dingo-sdk" >> $GITHUB_ENV

    - name: Check environment
      run: |
        echo "THIRD_PARTY_INSTALL_PATH: $THIRD_PARTY_INSTALL_PATH"
        echo "DINGOSDK_INSTALL_PATH: $DINGOSDK_INSTALL_PATH"

    #- name: Checkout dingo-sdk
    #  run: |
    #    git clone https://github.com/dingodb/dingo-sdk.git /tmp/dingo-sdk

    #- name: Build dingo-sdk
    #  run: |
    #    cd /tmp/dingo-sdk
    #    git submodule sync --recursive
    #    git submodule update --init --recursive
    #    mkdir build && cd build && cmake -DTHIRD_PARTY_INSTALL_PATH=/root/.local/dingo-eureka -DCMAKE_INSTALL_PREFIX=/root/.local/dingo-sdk ..
    #    make -j $(nproc)

    - name: Record event type
      run: |
        
        branchName=$(echo "${{ github.ref_name }}")
        echo "branch name is: $branchName"
        echo "$branchName" > branch_name.txt

        commitId="${{ github.sha }}"
        shortCommitId=${commitId:0:7}
        echo "commit id is: $shortCommitId"
        echo "$shortCommitId" > commit_id.txt

        echo "hello dingofs" > event.txt
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "pull_request" > event.txt
        elif [ "${{ github.event_name }}" == "push" ]; then
          echo "event type is push, github.ref is ${{ github.ref }}"
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "tag" > event.txt
            tagInfo=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
            echo "$tagInfo" > tag_name.txt
            echo "TAG_NAME=$tagInfo" >> $GITHUB_ENV
            echo "change event type to tag, tag info is: $tagInfo"
          else
            echo "push" > event.txt
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          fi
        fi
    
    - name: Save event type info
      uses: actions/upload-artifact@v4
      with:
        name: event
        path: event.txt
        compression-level: 0
    
    - name: Save tag name info
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: tag_name
        path: tag_name.txt
        compression-level: 0

    - name: Save branch name info
      uses: actions/upload-artifact@v4
      with:
        name: branch_name
        path: branch_name.txt
        compression-level: 0

    - name: Save commit id info
      uses: actions/upload-artifact@v4
      with:
        name: commit_id
        path: commit_id.txt
        compression-level: 0

    #- name: Set Safe Dir
    #  run: git config --global --add safe.directory $PWD

    #- name: Build dependencies
    #  run: make file_dep
 
    #- name: Build dingofs
    #  run: make file_build only=//src/* release=1

    #- name: Install dingofs
    #  run: |
    #    make file_deploy_config 

    - name: Test Random generate file
      run: |
        dd if=/dev/urandom of=randomfile bs=1M count=10

    - name: Archive the dingofs directory
      run: |
        tar -czvf dingofs.tar.gz randomfile

    - name: Check disk size
      run: |
        echo "Disk size after build:"
        df -h

    - name: Remove /root/.local/dingo-eureka
      run: |
        rm -rf /root/.local/dingo-sdk

    - name: Check disk size
      run: |
        echo "Disk size after remove eureka:"
        df -h

    - name: Copy artifactory to another workflow
      uses: actions/upload-artifact@v4
      with:
          name: dingofs
          path: ./dingofs.tar.gz
          compression-level: 0

    - name: Release
      uses: softprops/action-gh-release@v2
      # if: ${{ github.event_name == 'push'}}
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
      with:
        files: dingofs.tar.gz
        name: ${{ env.TAG_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        token: ${{ secrets.GH_TOKEN }}

